/**
 * @File Name          : IDebugLogger.cls
 * @Description        : 
 * @Author             : Thomas Wilkins
 * @Group              : 
 * @Last Modified By   : Thomas Wilkins
 * @Last Modified On   : 3/4/2020, 2:55:51 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    3/4/2020   Thomas Wilkins     Initial Version
**/
public interface IDebugLogger {
    void debug();
}
