/**
 * @File Name          : IWarningLogger.cls
 * @Description        : 
 * @Author             : Thomas Wilkins
 * @Group              : 
 * @Last Modified By   : Thomas Wilkins
 * @Last Modified On   : 3/4/2020, 2:57:39 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    3/4/2020   Thomas Wilkins     Initial Version
**/
public interface IWarningLogger {
    void warn();
}
